run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m
  tests: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gofumpt
    - gci
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - maintidx
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - unconvert
    - unused
    - unparam
    - misspell

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - blank # blank imports
      - dot # dot imports
      - prefix(github.com/cometbft/cometbft)
      - prefix(github.com/cosmos)
      - prefix(cosmossdk.io)
      - prefix(github.com/cosmos/cosmos-sdk)
      - prefix(github.com/CosmosContracts/juno)
  gosec:
    excludes:
      - G404
      - G115
  govet:
    disable:
      - printf

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
