# This is a basic workflow that is manually triggered

name: juno

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    runs-on: ubuntu-latest

    name: juno airdrop
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

          
      - name: Compile Juno
        run: |
          go mod download
          cd cmd/junod
          go build .

      - name: airdrop snapshot
        run: |
          cd cmd/junod
          wget https://raw.githubusercontent.com/CosmosContracts/mainnet/main/exchanges.json
          cat exchanges.json
          wget https://github.com/cosmos/mainnet/raw/master/genesis.cosmoshub-4.json.gz
          gzip -d genesis.cosmoshub-4.json.gz
          mv genesis.cosmoshub-4.json genesis.json
          if [ $(echo '{"test":true}' | jq empty > /dev/null 2>&1; echo $?) -eq 0 ]; then
          echo "JSON is valid"
          else
          echo "JSON is invalid"
          fi
          ./junod export-airdrop-snapshot juno genesis.json exchanges.json snapshot.json --juno-whalecap=50000000000

 # junod export-airdrop-snapshot [airdrop-to-denom] [input-genesis-file] [input-exchange-addresses] [output-snapshot-json] --juno-whalecap=[juno-whalecap] [flags]


      - name: add airdrop accounts
        run: ./junod add-airdrop-accounts
          
      - uses: actions/upload-artifact@v2
        with:
          name: junod 
          path: cmd/junod/junod
