---
name: Contract CI

on:
  pull_request:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker compose
        run: STAKE_TOKEN="ujunox" docker-compose up -d
      - name: Run deploy script
        run: |
          chmod a+x ./scripts/whoami/deploy_ci.sh
          ./scripts/whoami/deploy_ci.sh
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
