name: Make runner

on:
  workflow_call:
    inputs:
      make-command:
        type: string
        required: true
        description: 'The make command to run'
      branch-tag:
        type: string
        required: true
        description: 'The branch tag of the docker image'


jobs:
  run_make:
    runs-on: ubuntu-latest
    steps:
      - name: checkout chain
        uses: actions/checkout@v2

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version: 1.19
        id: go

      - run: make ${{ inputs.make-command }}
        env:
          BRANCH_CI: ${{ inputs.branch-tag }}